#!/bin/sh
ARGS=""
NAME=geiger-collect-daemon
PATH=/bin:/usr/bin:/sbin:/usr/sbin:.
DAEMON=/home/root/gumstix-rng/sbin/geiger-collect.py
PIDFILE=/var/run/$NAME.pid

export PATH

case "$1" in
  start)
    echo -n "Starting hardware RNG:  $NAME"
    start-stop-daemon --start --quiet --background --pidfile $PIDFILE --make-pidfile --exec $DAEMON -- $ARGS
    ;;

  stop)
    echo -n "Stopping hardware RNG:  $NAME"
    start-stop-daemon --stop --signal 3 --quiet --pidfile $PIDFILE 
    ;;

  restart)
    $0 stop
    $0 start
    exit $?
    ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
    exit 1
    ;;
esac

if ! [ $? = 0 ]; then
	echo " failed"
	exit 1
else
	echo " "
	exit 0
fi
